language: python

matrix:
  include:
    - python: "2.7"

before_install:
    # update aptitude
    - sudo apt-get update
    - sudo apt-get install -y python-opencv

    # help python importing cv2
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/pymodules/python$TRAVIS_PYTHON_VERSION

    # verify all requirements were met
    - INSTALLDIR=$(python -c "import os; import numpy; import cv2; print(os.path.dirname(cv2.__file__))")

install:
    - make install

script:
    - make test
